### PR TITLE
GSoC

### PR DESCRIPTION
**Pull request by kgugala**
This PR add GSoC page. It also includes #21 rebased on top of current master

### CODE REVIEW

**Comment by mithro** [comment]
Could you attach a screenshot so I can see what this looks like?

**Comment by kgugala** [comment]
screenshot-localhost-3000-2019 02 07-12-20-48

**Comment by kgugala** [comment]
@mithro is this OK

**Comment by mithro** [comment]
LGTM, feel free to merge.

**Comment by kgugala** [comment]
It seems I don't have merge rights here

**Pull request merged**
